#%RAML 1.0 DocumentationItem
title:  Shopping Cart for Splunk Products
content: |
  **Splunk eCommerce Website** enables Splunk to sell its product online.

  This API is for Customers Shopping Splunk Products and how they are going to use their Shopping Cart.

  Customers will be able to add, update and delete items from their respective cart.

  Once done, Customers will be able to place Orders by checking out their items from the cart.