#%RAML 1.0 DataType
type: object
properties:
  itemId:
    type: string
    required: true
    description: Unique ProductId
  itemName:
    type: string
  itemDescription?:
    type: string
  quantity:
    type: number
