#%RAML 1.0 Trait
headers:
  Authorization:
    type: string
    required: true
    description: JWT Basic Token Validation based on Header and ClaimBody based on aud=splunk and sub=shoppingcart and iss=architect