#%RAML 1.0 Trait

uses:
  datatypeLib:  ../library/ShoppingCartDatatypeLibrary.raml
body:
  application/json:
    type: datatypeLib.shoppingCartCollection
    example: !include ../examples/ShoppingCarts.json